### ISSUE TITLE
markdown fields rendered as `<IPython.core.display.Markdown object>`

### ISSUE THREAD

**Issue by matiasdahl** [jupyter/nbconvert#145]
The following creates a Markdown-formatted output cell:

![example](https://cloud.githubusercontent.com/assets/10188263/10711052/d65be130-7a78-11e5-8171-1597fe797edb.png)

Viewing the saved .ipynb file shows the following fields in the above cell's `outputs` fields:

```
 "data": {
      "text/markdown": [
       "*Markdown*"
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
  }
```
However, when converting the notebook to markdown using nbconvert as
```
   jupyter nbconvert --execute --to markdown md_output.ipynb --stdout
```
the cell's output is rendered as `<IPython.core.display.Markdown object>` (and not as *Markdown*).
This seems similar to  [issue 7394](https://github.com/ipython/ipython/issues/7394) for ipython.

-----

In markdown.tpl, the output is rendered by the [following block](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/markdown.tpl#L59-L61):

```
{% block data_text scoped %}
{{ output.data['text/plain'] | indent }}
{% endblock data_text %}
```
A (quick?) workaround is to just override the block by using the following template:
```
{%- extends 'markdown.tpl' -%}

{% block data_text scoped %}
{{ output.data['text/markdown'] }}
{% endblock data_text %}
```

(Jupyter 4.0.6)

**Comment by minrk** [comment]
This is already fixed in master.

**Comment by vatsan** [comment]
I am on Jupyter 4.2.1, the issue still exists. Opening a saved Jupyter notebook that contained "Markdowns" programatically rendered inline in output cells show up as "<IPython.core.display.Markdown object>" instead of actually rendering as text.

Are there any workarounds I could try?

**Comment by vatsan** [comment]
FWIW I have upgraded to Jupyter 4.4.0 and the issue still remains. 
I have the following line in my Jupyter notebook:

display(Markdown('### 1. Loading datasets'))

This shows up as the following when I open the notebook on another host:

<IPython.core.display.Markdown object>

**Comment by takluyver** [comment]
Your notebook is probably loading as untrusted. See the [security docs](http://jupyter-notebook.readthedocs.io/en/stable/security.html#security-in-notebook-documents) for an explanation of what that means and when a notebook is untrusted.
