### ISSUE TITLE
DeprecationWarning: 'contextfilter' is renamed to 'pass_context'

### ISSUE THREAD

**Issue by slayoo** [jupyter/nbconvert#1568]
https://github.com/jupyter/nbconvert/blob/d7c286b9bd07a8670d8ab08469c2e266140522c1/nbconvert/exporters/html.py#L14

As discussed here: https://github.com/pallets/jinja/issues/1381
``contextfilter`` is now deprecated.

This causes the following warning to show up whenever using the exporters:
```
...
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/nbconvert/exporters/html.py:100: in HTMLExporter
    def markdown2html(self, context, source):
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jinja2/filters.py:54: in contextfilter
    warnings.warn(
E   DeprecationWarning: 'contextfilter' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
```

Thanks

**Comment by sjdemartini** [comment]
This should presumably have been fixed in https://github.com/jupyter/nbconvert/pull/1624

**Comment by slayoo** [comment]
thanks!

**Comment by twhughes** [comment]
Hi, I am still getting this warning with nbconvert.  Version: 6.1.0

Is there a way to resolve?

**Comment by dimpase** [comment]
`contextfilter` is removed in the current `jinja2` version, 3.1.1, on PyPI.
So fixing this is getting urgent.
