### ISSUE TITLE
Incorrect conversion of matplotlib SVG plots

### ISSUE THREAD

**Issue by goyodiaz** [jupyter/nbconvert#1849]
Steps to reproduce:
* Display a matplotlib SVG plot in a notebook.
* Export as HTML
* There is no plot in the output.

[Notebook showing the issue](https://github.com/jupyter/nbconvert/files/9404089/svg_plot.txt)
[nbconvert output](https://github.com/jupyter/nbconvert/files/9404095/svg_plot_html.txt)

Screenshot of the notebook:
![notebook](https://user-images.githubusercontent.com/1676326/186203471-e63d2f6a-dc8a-45fa-a413-5872f18936c6.png)

Screenshot of the HTML output:
![nbconvert_output](https://user-images.githubusercontent.com/1676326/186203467-0b77614c-1522-4f8f-92dc-2d311614f9bc.png)

**Nbconvert version:** 7.0.0

**Comment by adl** [comment]
This is related to #1836

**Comment by goyodiaz** [comment]
@adl Yes, I guess `clean_html` is returning `bytes` now and the output needs to be decoded again.

**Comment by adl** [comment]
The encoding expains the `b'...'` in the output, but the more serious issue is that `clean_html` seems to strips all tags inside the `<svg>...</svg>` element, making `<svg>` useless.

**Comment by goyodiaz** [comment]
I guess that can be fixed by using a custom `Cleaner` object, but I have no idea how to express that in the template.

**Comment by adl** [comment]
An additional point. 

Looking at the templates, I find weird that HTML is conditionally passed through `clean_html` with:

```
{%- if resources.should_sanitize_html %}
{{ output.data['text/html'] | clean_html }}
{%- else %}
{{ output.data['text/html'] }}
{%- endif %}
```
where `should_sanitize_html` defaults to False, while SVG goes through `clean_html` unconditionally.

**Comment by adl** [comment]
@martinRenou and @SylvainCorlay this `clean_html` was added by 4a5eeb42ce3f65799a38fee785a5c84c38ea4ad9.  Can you comment?

**Comment by adl** [comment]
With #1854 the implementation of `clean_html` has changed to only allow a handful of tags, and escape everything else.  So instead of a blank SVG image, we can now see the SVG source in the rendered HTML.

**Comment by luboshanus** [comment]
Any changens? 
nbconvert 7.2.2 still doing the SVG source in html. Thought at first, it is julia thing https://github.com/jheinen/GR.jl/issues/482

**Comment by JBlaschke** [comment]
Urgh -- I wasted loads of time trying to make a high-res png plot "look" like an svg, and I finally gave up and used: https://github.com/jupyter/nbconvert/issues/1836#issuecomment-1291258577

**Comment by akx** [comment]
This should be fixed by https://github.com/jupyter/nbconvert/pull/1890 ...

**Comment by luboshanus** [comment]
`nbconvert 7.2.3`

I still have a problem with convert.

in julia 1.8.2., from `notebook` to `html`

<img width="374" alt="Screenshot 2022-11-01 at 16 24 40" src="https://user-images.githubusercontent.com/2473206/199271159-b0412db0-2645-402e-a60d-86d9a8864961.png">

**Comment by desilinguist** [comment]
Yes, I am seeing the same issue as @luboshanus and just seeing black canvases.

**Comment by torext** [comment]
Running 7.2.5 and seeing the same as @luboshanus & @desilinguist.

**Comment by desilinguist** [comment]
I posted a workaround [here](https://github.com/jupyter/nbconvert/issues/1894#issuecomment-1334355109).
