### ISSUE TITLE
Download as pdf via LaTex not working

### ISSUE THREAD

**Issue by cniedotus** [jupyter/nbconvert#27]
[#143 at IRKernel](https://github.com/IRkernel/IRkernel/issues/143)

**Comment by takluyver** [comment]
Copying what I suspect is the relevant part of the Latex output:

```
[1{/usr/local/texlive/2013/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
[2]

! LaTeX Error: Environment description* undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type H for immediate help.
...

l.423 \begin{description*}

?
! Emergency stop.
...

l.423 \begin{description*}

! ==> Fatal error occurred, no output PDF file produced!
```

**Comment by clarknie** [comment]
Any idea about how I can fix it? The Download as pdf function works for Python 2 Kernel.

**Comment by takluyver** [comment]
Sorry, I don't really know about latex. Try to work out what bit of output it's choking on, that might help.

**Comment by alvinwt** [comment]
I tried generating the pdf using nbconvert and it failed at the compilation step. When I do pdflatex on the generated .tex file it works. A workaround might be using nbconvert at the commandline and compiling using pdflatex.

**Comment by dkincaid** [comment]
It would be really nice to get this fixed. Any estimate of when it might get fixed?

**Comment by takluyver** [comment]
I think it's waiting for someone who knows LaTeX to investigate what's going on. Volunteers welcome :-)

**Comment by dkincaid** [comment]
Well, I know Latex well, but don't know anything about how all this Jupyter/IRKernel/nbconvert connects together. I'll see if I can poke around a bit.

**Comment by takluyver** [comment]
You can generate the LaTeX by doing nbconvert by `--to latex`, and then run pdflatex on that. Although @alvinwt reports that that makes the bug disappear for him, so I'm not sure what's going on. The latex->pdf conversion code is here: https://github.com/jupyter/nbconvert/blob/0e6466d7a5815187b5f592b6f21025e5ef2aa851/nbconvert/exporters/pdf.py#L127

**Comment by dkincaid** [comment]
The problem is that for some reason the export is using "description*" as the list environment. As far as I know there is no such environment. At least not one in any of the common libraries. It should really be changed to "description" instead, but I cannot find where that typo is in the code. Can anyone help find it or at least point me to where it might be?

**Comment by alvinwt** [comment]
Hi @dkincaid, I tried looking for the description* tag and it's not in the nbconvert templates as well. Interestingly, the description* block matches the output of the IRKernel. 

````
\begin{description*}
\item[X56403463.1727.4c23.a709.de5f168c4073] 50.0006258799053
\item[ca8afb2c.be3d.41e8.8dbc.19fe7ab6154b] 30.3254246898821
\item[CHC433] 21.169034458756
\item[X65e430e1.0c9a.4045.83a9.653b7cff811d] 14.2808853888554
\item[X6dcfc418.ab28.4365.95ea.c1ae254f2341] 11.8185201121792
\end{description*}
````

json from notebook
````
      "text/latex": [
       "\\begin{description*}\n",
       "\\item[X56403463.1727.4c23.a709.de5f168c4073] 50.0006258799053\n",
       "\\item[ca8afb2c.be3d.41e8.8dbc.19fe7ab6154b] 30.3254246898821\n",
       "\\item[CHC433] 21.169034458756\n",
       "\\item[X65e430e1.0c9a.4045.83a9.653b7cff811d] 14.2808853888554\n",
       "\\item[X6dcfc418.ab28.4365.95ea.c1ae254f2341] 11.8185201121792\n",
       "\\end{description*}\n"
````

*Output from the notebook*
````
Out[72]:
X56403463.1727.4c23.a709.de5f168c4073
50.0006258799053
ca8afb2c.be3d.41e8.8dbc.19fe7ab6154b
30.3254246898821
CHC433
21.169034458756
X65e430e1.0c9a.4045.83a9.653b7cff811d
14.2808853888554
X6dcfc418.ab28.4365.95ea.c1ae254f2341
11.8185201121792
````

Interestingly the description tag is in the .ipynb file and rendered in the  "text/latex" section in the output. I'm not sure how the notebook handles this but I couldn't find the same section in my notebook with the python kernels.

**Comment by takluyver** [comment]
Aha! I hadn't thought of this coming from the kernel itself. It looks like the relevant code is here:

https://github.com/IRkernel/repr/blob/1f37cacab435d29da5e0679a4be75bd0899ab565/R/repr_vector.r#L122

And here's the commit that added it: https://github.com/IRkernel/repr/commit/8f50f10d5ac53e32bd274d4d96ed1f72ea34fa9a

@flying-sheep, the `description*` environment seems to be causing problems in nbconvert. Any thoughts on what can be done?

**Comment by flying-sheep** [comment]
> what can be done?

add a way to register stuff to add to the latex preample of the template.

right now the default template has a rather random assortment of stuff that fits specifically the needs of ipython’s output. that’s not flexible anough, and we can’t add everything everyone would ever want.

as documented in `help(repr-package)`, it needs `\usepackage[inline]{enumitem}` and possibly `\usepackage{minted}`

**Comment by dkincaid** [comment]
I can confirm that adding `\usepackage[inline]{enumitem}` fixes the problem with the missing `description*` environment. However, I don't see that documented in `help(package = 'repr'` as was suggested.

Adding `minted` causes other issues, so I would recommend against including that.

Please don't forget about the issue with `%` characters not being escaped as well. That will cause additional compilation errors once the description error is resolved.

**Comment by flying-sheep** [comment]
oh sorry, i meant `package?repr`

> Please don't forget about the issue with % characters not being escaped as well. That will cause additional compilation errors once the description error is resolved.

noted!

**Comment by dkincaid** [comment]
This piece of code:

```
quantile(raw_in_gb, seq(0.1,1,0.1))
```

produces this output in Jupyter notebook:
```
10% 0
20% 0
30% 0
40% 0.0000892743291503907
50% 0.0007269946
60% 0.00906304677999997
70% 0.0788954083100001
80% 0.56371782982
90% 2.9702177811
100% 394.2425975632
```

and this output in latex after `nbconvert` is run:
```
    \begin{description*}
\item[10%] 0
\item[20%] 0
\item[30%] 0
\item[40%] 0.0000892743291503907
\item[50%] 0.0007269946
\item[60%] 0.00906304677999997
\item[70%] 0.0788954083100001
\item[80%] 0.56371782982
\item[90%] 2.9702177811
\item[100%] 394.2425975632
\end{description*}
```

in Latex the `%` characters need to be escaped as `\%`

**Comment by flying-sheep** [comment]
hmm, right. tracked as IRkernel/repr#10

**Comment by matrs** [comment]
So this problem is still here, any news?
> LaTeX Error: Environment enumerate* undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
l.303     \begin{enumerate*}                      
? 
! Emergency stop.
 ...                                                                                         
l.303     \begin{enumerate*}
!  ==> Fatal error occurred, no output PDF file produced! >

**Comment by flying-sheep** [comment]
as said above, that’s due to

1. my choice to use tzhe enumitem package
2. the default latex template hardcoding the packages that someone at some point decided IPython would use

you can put this in a file `r.tplx`:

```latex
((*- extends 'article.tplx' -*))

((* block packages *))    
    ((( super() )))

    \usepackage[inline]{enumitem}
    \usepackage{minted}
((* endblock packages *))
```

and then call `nbconvert --to=pdf --template=r.tplx something.ipynb `

**Comment by matrs** [comment]
Thanks, but as it was mentioned earlier, that only works without package {minted}, once i erased that line it worked.
>Package ifplatform Warning: 
    shell escape is disabled, so I can only detect \ifwindows.

) (/usr/share/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texmf-dist/tex/generic/xstring/xstring.sty
(/usr/share/texmf-dist/tex/generic/xstring/xstring.tex))
(/usr/share/texmf-dist/tex/latex/lineno/lineno.sty))

! Package minted Error: You must invoke LaTeX with the -shell-escape flag.
>

Also, there are many rendering errors in the PDF, errors  that when I create a python nb instead of a R one , and use %%R cell magic and convert the nb to pdf don't happen.

**Comment by flying-sheep** [comment]
not an error. that’s the vector indices :smile:

if you want them to be displayed differently, read the [enumitem](ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/macros/latex/contrib/enumitem/enumitem.pdf) docs and find out how to configure them to show no indices.

**Comment by matrs** [comment]
Of course are the indexes but in  dont see them in R console, i dont see them in the the html, i dont see them in the pdf created from ipython using R magic so why i suppose to want them to be displayed in the pdf ? Not an error? displaying something that nobody sees , just this nbconvert want to display, perfect.

**Comment by flying-sheep** [comment]
haha no reason to get worked up either.

it’s just the representation i chose, because there’s no easy way to get “display index of the index of the first item per line” in LaTeX.

you can configure my representation by calling `\setlist` with the right options (one reason why i chose `enumitem` instead of “numbers with spaces between them” or plain enumerate. you just have to read the docs that i linked to :smiley_cat:

all this is a byproduct of using fancy displaying instead of ugly “render R’s output as monospaced text” (what R magic does).

please share the `\setitem` invocation that does what you want and i’ll put it in the docs :+1:

**Comment by gidden** [comment]
Hi all, any movement on this issue?

I added the following `r.tplx` to `~/.local/share/jupyter/templates`

```
((*- extends 'article.tplx' -*))

((* block packages *))
    ((( super() )))

    \usepackage[inline]{enumitem}
((* endblock packages *))
```

Then tried to convert my notebook

```
$ jupyter nbconvert --to pdf --template r.tplx hh_data.ipynb 
```

which resulted in the output [here](https://gist.github.com/gidden/df539841180e47b9b335). The important part is below:

```
! Missing $ inserted.
<inserted text> 
                $
l.281 ...SCRIPTION & URL & ISO3 & PERIOD & SURVEY_
                                                  NAME\\
? 
! Emergency stop.
<inserted text> 
                $
l.281 ...SCRIPTION & URL & ISO3 & PERIOD & SURVEY_
                                                  NAME\\
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.
```

Any help is appreciated. Cheers!

**Comment by flying-sheep** [comment]
can you try with the newest repr from github? this is a latex escaping error which was hopefully addressed in a recent PR

**Comment by gidden** [comment]
Hi @flying-sheep, I did a `devtools::install_github('IRkernel/repr', lib='~/.local/R/library', force=TRUE)`, still have the same error (both with file->download as and using the CLI).

**Comment by gidden** [comment]
Is it possible to confirm the R kernel version being used through a CLI or API in the notebook?

**Comment by flying-sheep** [comment]
sure, `packageVersion('packagename')`.

about the error: that’s really weird. [this line](https://github.com/IRkernel/repr/blob/da0ce5977621c574d054e58e8fece3df58102af8/R/repr_matrix_df.r#L181) should take care of col/rownames, and [those](https://github.com/IRkernel/repr/blob/da0ce5977621c574d054e58e8fece3df58102af8/R/repr_matrix_df.r#L190-L197) of values.

what object causes the breakage (contains `SURVEY_NAME`)? what does `repr::repr_latex(the_object)` output?

**Comment by gidden** [comment]
```
In [5]:

packageVersion('repr')

Out[5]:

[1] ‘0.4’

In [6]:

repr::repr_latex(dbReadTable(conn, 'SURVEY_DATA'))

Out[6]:
'
\begin{tabular}{r|lllllll}
  & SURVEY & COUNTRY & DESCRIPTION & URL & ISO3 & PERIOD & SURVEY\_NAME\\
\hline
1 & IND1 & India & NA & NA & IND & 2011-2012 & IND NSS 68 2011-2012\\
2 & BRA1 & Brazil & NA & NA & BRA & 2008-2009 & BRA POF 2008-2009\\
3 & GHA1 & Ghana & NA & NA & GHA & 2005-2006 & GHA GLSS5 2005-2006\\
4 & IND4 & India & NA & NA & IND & 2011-2012 & IND IHDS 2011-2012\\
5 & IND5 & India & NA & NA & IND & 2004-2005 & IND IHDS 2004-2005\\
6 & IND3 & India & NA & NA & IND & 2000-2001 & IND NSS 56 2000-2001\\
7 & IND2 & India & NA & NA & IND & 2004-2005 & IND NSS 61 2004-2005\\
8 & ZAF2 & South Africa & NA & NA & ZAF & 2005-2006 & ZAF IES 2005-2006\\
9 & IDN1 & Indonesia & NA & NA & IDN & 2007-2008 & IDN NSES July 2008\\
10 & BRA2 & Brazil & NA & NA & BRA & 2002-2003 & BRA POF 2002-2003\\
11 & ZAF1 & South Africa & Income and Expenditure Survey (IES) 2010-2011 & https://www.datafirst.uct.ac.za/dataportal/index.php/catalog/316 & ZAF & 2010-2011 & ZAF IES 2010-2011\\
12 & GHA2 & Ghana & NA & NA & GHA & 2012-2013 & GHA GLSS6 2012-2013\\
\end{tabular}
'
```

**Comment by flying-sheep** [comment]
well, it’s *not* the same. now it’s `\_` instead of `_`, which should be fine.

**Comment by gidden** [comment]
Perhaps this is a separate issue, then? I fully upgraded jupyter (from pip) and have tried to use both the GUI and CLI to convert, but still get failures. I tried converting to just latex and the table output is not the same as what `repr::repr_latex` provides (i.e., `jupyter nbconvert` does not appear to be using the latest IRkernel installed on my box).

**Comment by takluyver** [comment]
With the command you have above, nbconvert won't use IRkernel at all - it's working with the outputs saved in your notebook. You'll need to re-run the notebook after updating IRkernel to get the updated output.

There is a `--execute` flag for nbconvert which will make it re-run the code and regenerate the outputs.

**Comment by gidden** [comment]
Hi @takluyver, should have been more precise. I killed the notebook process after installing the updated kernel. Note that the `repr::repr_latex` output is actually copy-pasted from a notebook. The GUI download as feature still fails (500 internal server error `nbconvert failed: PDF creating failed`)

**Comment by gidden** [comment]
Ok, finally figured it out. I had to

1) update IRKernel
2) update jupyter
3) kill all active kernels and restart

Thanks for the assist!

**Comment by flying-sheep** [comment]
sorry to be nitpicky, but i think what you really *had* to do is

1. unload and reload `repr` in the kernel (probably easiest done by killing the kernel and restarting it)
2. recreate the cell output

dunno how updating jupyter or the kernel itself could help, but it never hurts :smile:

**Comment by andreapago** [comment]
Hi,
I have just discovered that I have this issue with
jupyterhub 0.6.1
underlying jupyter 4.1.0
R kernel installed following the https://irkernel.github.io/installation/ to what I suppose is the latest version

any idea how to solve it?
thanks

**Comment by flying-sheep** [comment]
read my first comment in this thread

**Comment by janschulz** [comment]
Note, the current workaround is adding something like this in the first cell (or at least before any displayed functions or lists/vectors):

```R
library("IRdisplay")
display_latex("\\usepackage[inline]{enumitem}\n\\usepackage{minted}"
```

There are now two alternative proposals to fix this without the need of a user workaround: https://github.com/IRkernel/repr/pull/74 and https://github.com/jupyter/nbconvert/pull/335

**Comment by flying-sheep** [comment]
wait, you can do that inside of `\begin{document}\end{document}`?

pretty cool, i didn’t know that!

**Comment by bbolker** [comment]
bump.  I just converted to LaTeX and did a search-and-replace for `enumerate* -> enumerate` before running pdflatex ... but it would be great to have a general solution

**Comment by flying-sheep** [comment]
check out #335 and #336

**Comment by michaelpacer** [comment]
I'm going to say #335 closes this but will reopen if there it pops up again.
